'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const html = read('www/index.html'), css = read('www/css/style.css'), game = read('www/js/game.js');
const tokens = read('www/js/token-system.js'), evolution = read('www/js/token-evolution.js');
const online = read('www/js/online.js'), migration = read('supabase/migrations/20261006013000_token_2_0_profile_identity.sql');
const migrationSql = migration.replace(/^\s*--.*$/gm, '');
const gradle = read('android/app/build.gradle'), pkg = JSON.parse(read('package.json'));
let checks = 0;
function ok(value, message) { assert.ok(value, message); checks++; console.log('  ok - ' + message); }

console.log('hero-tokens.test.js');
ok(pkg.version === '1.7.3', 'package version is 1.7.3');
ok(/versionCode 27/.test(gradle) && /versionName "1\.7\.3"/.test(gradle), 'Android package metadata is aligned');
ok(/Crossfour v1\.7\.3/.test(html) && /css\/style\.css\?v=1\.7\.3/.test(html), 'footer and asset cache keys are aligned');
ok(html.indexOf('js/token-system.js') < html.indexOf('js/token-evolution.js') && html.indexOf('js/token-evolution.js') < html.indexOf('js/game.js'), 'TokenSystem loads before evolution and gameplay');
ok(/viewBox="0 0 24 24"/.test(tokens) && /<circle class="gem-rim-outer"/.test(tokens) && /<circle class="gem-body"/.test(tokens), 'procedural artwork preserves the circular body and metallic rim');
ok(/gem-facet-light/.test(tokens) && /gem-facet-dark/.test(tokens) && /gem-sheen/.test(tokens) && /gem-spec/.test(tokens) && /gem-shadow/.test(tokens), 'crystal facets, layered specular reflection, and contact shadows are original SVG layers');
ok(/gem-num-rim/.test(tokens) && /gem-num-disc/.test(tokens) && /class="gem-num number-/.test(tokens), 'raised number disc and skin-specific numeral are included');
ok(/SEAT_SHAPES/.test(tokens) && /id: 'ruby'/.test(game) && /id: 'emerald'/.test(game) && /id: 'gold'/.test(game) && /id: 'sapphire'/.test(game), 'four distinct per-player metallic materials remain data-driven');
ok(['classic', 'royal', 'dragon', 'cyber', 'galaxy', 'fire', 'ice', 'shadow', 'diamond', 'legendary'].every(id => new RegExp("id: '" + id + "'").test(tokens)), 'all ten requested original skins are present');
ok(/roman/.test(tokens) && /digital/.test(tokens) && /ancient/.test(tokens) && /carved/.test(tokens), 'Royal, Cyber, Ancient/Galaxy, and Dragon number treatments are available');
ok(/TOKEN_CAPTURE_MS = 680/.test(game) && /token-capture-wave/.test(game) && /capture-settle/.test(game), 'capture shockwave/settle effects are bounded to 680ms');
ok(/prefersReducedMotion\(\).*placeToken/.test(game) && /prefers-reduced-motion: reduce/.test(css), 'captured token transitions and decorative motion respect reduced-motion preferences');
ok(/token-trail-dot/.test(game + css) && /TRAILS/.test(tokens), 'short, skin/set-themed movement trails are available');
ok(/tokenIdentityForSeat/.test(game) && /token-intro-grid/.test(html), 'player identity is carried into accessible board tokens and match-intro UI');
ok(/syncTokenIdentity: syncTokenIdentity/.test(online) && /token_skin: chosen\.skin, token_set: chosen\.set, token_level: chosen\.level/.test(online), 'only the authenticated owner can sync skin, set, and level fields');
ok(/grant update \(token_skin, token_set, token_level\)[\s\S]*?to authenticated/i.test(migrationSql) && !/create policy|grant[\s\S]{0,100}wallet|grant[\s\S]{0,100}currency/i.test(migrationSql), 'unapplied migration grants only additive token columns and leaves existing profile RLS in place');
ok(/function collectEligible/.test(evolution) && /matchesRequired/.test(evolution) && !/coinCost|coin|diamond|purchase|wins/i.test(evolution), 'evolution progression has no coins, diamonds, purchase, or win-count path');
ok(/token-system\.test\.js/.test(pkg.scripts.test) && /test:token2-browser/.test(JSON.stringify(pkg.scripts)), 'TokenSystem unit and responsive browser suites are registered');
ok(!/Ludo Star|Yalla|yalla|ludostar/i.test(game + css + tokens), 'Token 2.0 uses original art, with no third-party game asset references');
console.log('\nhero-token checks passed (' + checks + ' checks).');
