'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const migrations = fs.readdirSync(path.join(root, 'supabase/migrations'));
const name = migrations.find(file => /_ludo_chess\.sql$/.test(file));
assert.ok(name, 'Ludo Chess migration exists');
const sql = read('supabase/migrations/' + name);
const online = read('www/js/online.js');
const html = read('www/index.html');
const resignMigrationName = migrations.find(file => /_allow_out_of_turn_chess_resignation\.sql$/.test(file));
assert.ok(resignMigrationName, 'out-of-turn resignation migration exists');
const resignSql = read('supabase/migrations/' + resignMigrationName);
let checks = 0;
function ok(value, message) { assert.ok(value, message); checks++; console.log('  ok -', message); }

ok(/create table if not exists public\.ludo_chess_matches/i.test(sql) && /alter table public\.ludo_chess_matches enable row level security/i.test(sql), 'Chess state has a dedicated table with RLS enabled');
ok(/Room members can read Ludo Chess matches[\s\S]*?room_members[\s\S]*?auth\.uid\(\)/i.test(sql), 'only authenticated room participants can read Chess match state');
ok(/revoke all on public\.ludo_chess_matches from anon, authenticated[\s\S]*?grant select on public\.ludo_chess_matches to authenticated/i.test(sql), 'clients have read-only Chess table access');
ok(/alter table public\.rooms[\s\S]*?ludo_chess[\s\S]*?alter table public\.match_history[\s\S]*?ludo_chess/i.test(sql), 'room and match history constraints include the new mode');
ok(/Ludo Chess requires exactly two seats/i.test(sql) && /v_room\.capacity <> 2 or v_count <> 2/i.test(sql), 'room creation and start enforce exactly two players');
ok(/create or replace function public\.start_room/i.test(sql) && /insert into public\.ludo_chess_matches/i.test(sql), 'the existing ready/host flow initializes a separate Chess state row');
for (const fn of ['ludo_chess_move', 'claim_ludo_chess_draw', 'resign_ludo_chess']) {
  ok(new RegExp('create or replace function public\\.' + fn + '\\(', 'i').test(sql), fn + ' is a dedicated RPC');
  ok(new RegExp('grant execute on function public\\.' + fn + '\\(', 'i').test(sql), fn + ' is available to authenticated players');
}
const moveStart = sql.indexOf('create or replace function public.ludo_chess_move(');
const moveEnd = sql.indexOf('$$;', moveStart);
const moveBody = sql.slice(moveStart, moveEnd);
ok(moveBody.indexOf('public.rooms as r') < moveBody.indexOf('public.ludo_chess_matches as m') && moveBody.indexOf('public.ludo_chess_matches as m') < moveBody.indexOf('private.online_match_actions as a'), 'move RPC locks room and state before idempotency lookup');
ok(/auth\.uid\(\)[\s\S]*?You are not a member of this room[\s\S]*?v_state->>'turn'[\s\S]*?v_seat/i.test(moveBody), 'move RPC verifies authentication, room membership, and the assigned turn');
ok(/p_expected_version <> v_version[\s\S]*?private\.ludo_chess_legal/i.test(moveBody), 'move RPC rejects stale versions and independently validates legal moves');
ok(/primary key \(room_id, action_id\)/i.test(read('supabase/migrations/20261004100500_online_authoritative_match.sql')) && /v_existing\.actor_id <> v_user or v_existing\.request <> v_request/i.test(moveBody), 'Chess actions reuse actor- and payload-bound idempotency');
ok(/en.passant/i.test(sql) && /castling/i.test(sql) && /p_promotion/i.test(sql) && /checkmate/i.test(sql) && /stalemate/i.test(sql), 'server rules cover en passant, castling, promotion, checkmate, and stalemate');
const legalStart = sql.indexOf('create or replace function private.ludo_chess_legal(');
const legalEnd = sql.indexOf('$$;', legalStart);
const legalBody = sql.slice(legalStart, legalEnd);
const applyStart = sql.indexOf('create or replace function private.ludo_chess_apply(');
const applyEnd = sql.indexOf('$$;', applyStart);
const applyBody = sql.slice(applyStart, applyEnd);
ok(/v_promo text := pg_catalog\.lower\(coalesce\(p_promotion, ''\)\)/i.test(legalBody) && /if v_tr = v_last then[\s\S]*?v_promo not in \('q','r','b','n'\) then return false/i.test(legalBody), 'server promotion legality accepts exactly queen, rook, bishop, or knight and rejects a missing choice');
ok(/elsif p_promotion is not null then return false/i.test(legalBody), 'server rejects promotion parameters on ordinary non-promotion moves');
ok(/v_moved := case when v_color = 0 then pg_catalog\.upper\(pg_catalog\.lower\(p_promotion\)\) else pg_catalog\.lower\(p_promotion\) end/i.test(applyBody) && /'promotion',case when p_promotion is null then null else pg_catalog\.lower\(p_promotion\) end/i.test(applyBody), 'server applies and records the exact selected promotion with the correct Red/Blue piece case');
ok(/'promotion',p_promotion/i.test(moveBody) && moveBody.indexOf('select a.* into v_existing') < moveBody.indexOf("if p_expected_version <> v_version") && /return v_existing\.response \|\| pg_catalog\.jsonb_build_object\('duplicate',true\)/i.test(moveBody), 'RPC binds the promotion choice to its idempotency payload and resolves exact duplicates before stale-version rejection');
ok(/draw_seventy_five_moves/i.test(sql) && /draw_fivefold_repetition/i.test(sql) && /draw_insufficient_material/i.test(sql) && /claimable/i.test(sql), 'server recognizes automatic and claimable standard draw conditions');
ok(/alter publication supabase_realtime add table public\.ludo_chess_matches/i.test(sql), 'Chess state is added to Realtime publication');
const resignStart = resignSql.indexOf('create or replace function public.resign_ludo_chess(');
const resignEnd = resignSql.indexOf('$$;', resignStart);
const resignBody = resignSql.slice(resignStart, resignEnd);
ok(resignStart >= 0 && resignEnd > resignStart, 'resignation migration replaces the existing authenticated RPC');
ok(/You are not a member of this room/i.test(resignBody) && /v_status <> 'active'/i.test(resignBody) && /p_expected_version <> v_version/i.test(resignBody), 'resignation still requires an authenticated room member, an active room, and the current version');
ok(/v_existing\.actor_id<>?v_user[\s\S]*?v_existing\.request<>?v_request/i.test(resignBody) && /room_id,action_id,actor_id,request,response/i.test(resignBody), 'out-of-turn resignations retain actor-bound idempotent persistence');
ok(!/v_state->>'turn'\)::integer <> v_seat/i.test(resignBody), 'the resigning participant is not incorrectly restricted to the side-to-move');
ok(/\{winner\}[\s\S]*?1-v_seat/i.test(resignBody) && /update public\.rooms set status='completed'/i.test(resignBody) && /update public\.match_history set status='completed'/i.test(resignBody), 'resignation awards the opponent and completes the room and history atomically');
const resignVisibility = online.match(/\$\('online-chess-resign'\)\.classList\.toggle\('hidden', ([^;]+)\);/);
ok(!!resignVisibility && /state\.phase !== 'active'/.test(resignVisibility[1]) && !/isMyTurn/.test(resignVisibility[1]), 'the resign control is available for either player during an active game');
ok(/table: 'ludo_chess_matches'/i.test(online) && /ludo_chess_move/i.test(online), 'the signed-in client subscribes to and acts on the Chess match table');
ok(/value="ludo_chess"/i.test(html) && /online-chess-board/i.test(html), 'online lobby offers Chess and has a dedicated playable board');
ok(!/ludo_chess|LudoChess/.test(read('www/js/logic.js') + read('www/js/save-store.js')), 'Classic Ludo engine and local save format are not changed by Chess');
const drawOfferMigration = migrations.find(file => /_online_chess_draw_offers\.sql$/.test(file));
ok(drawOfferMigration, 'a forward-only mutual Chess draw-offer migration exists');
const drawSql = read('supabase/migrations/' + drawOfferMigration);
const offerStart = drawSql.indexOf('create or replace function public.offer_ludo_chess_draw(');
const offerEnd = drawSql.indexOf('$$;', offerStart);
const offerBody = drawSql.slice(offerStart, offerEnd);
const respondStart = drawSql.indexOf('create or replace function public.respond_ludo_chess_draw(');
const respondEnd = drawSql.indexOf('$$;', respondStart);
const respondBody = drawSql.slice(respondStart, respondEnd);
ok(/add column if not exists draw_offer jsonb/i.test(drawSql) && /position_version/i.test(drawSql) && !/position_key|ludo_chess_position_key/i.test(drawSql), 'pending offers are stored on the authoritative match row and bound to its locked position version without an external helper');
ok(/create trigger ludo_chess_matches_clear_draw_offer[\s\S]*?before update of state, version, draw_offer on public\.ludo_chess_matches/i.test(drawSql) && /new\.state->>'phase' = 'over'[\s\S]*?new\.state is distinct from old\.state[\s\S]*?new\.version is distinct from old\.version[\s\S]*?new\.draw_offer is not distinct from old\.draw_offer[\s\S]*?new\.draw_offer := null/i.test(drawSql) && !/ludo_chess_position_key/i.test(drawSql), 'a committed move, version change, or terminal result clears the pending offer atomically without a PR #14 helper');
ok(/new\.status = 'cancelled'[\s\S]*?update public\.ludo_chess_matches[\s\S]*?draw_offer = null/i.test(drawSql), 'room cancellation clears any pending offer');
for (const fn of ['offer_ludo_chess_draw', 'respond_ludo_chess_draw']) {
  ok(new RegExp('create or replace function public\\.' + fn + '\\(', 'i').test(drawSql), fn + ' is a dedicated server RPC');
  ok(new RegExp('grant execute on function public\\.' + fn + '\\(', 'i').test(drawSql), fn + ' is granted only through the authenticated role');
}
ok(/room_members as rm[\s\S]*?rm\.user_id = v_user[\s\S]*?You are not a member of this room/i.test(offerBody) && /v_status <> 'active'[\s\S]*?v_state->>'phase' <> 'active'/i.test(offerBody), 'only authenticated members of an active Chess match may offer');
ok(offerBody.indexOf('select a.* into v_existing') < offerBody.indexOf('if p_expected_version <> v_version') && /v_existing\.actor_id <> v_user or v_existing\.request <> v_request/i.test(offerBody), 'offer retries are actor/payload-bound and exact duplicates return before stale-version checks');
ok(/if p_expected_version <> v_version then[\s\S]*?raise exception 'Match state is stale/i.test(offerBody) && /position_version/.test(offerBody), 'offer creation rejects stale versions and captures the observed position version');
ok(/Only the player who offered the draw can withdraw it/i.test(respondBody) && /Only the other player can respond to this draw offer/i.test(respondBody), 'only the offerer may withdraw, and only the opponent may accept or decline');
ok(respondBody.indexOf('select a.* into v_existing') < respondBody.indexOf('if p_expected_version <> v_version') && /v_existing\.actor_id <> v_user or v_existing\.request <> v_request/i.test(respondBody), 'responses are idempotent and bound to actor, version, and decision');
ok(/p_response = 'accept'[\s\S]*?\{phase\}[\s\S]*?"over"[\s\S]*?\{result\}[\s\S]*?draw_agreement[\s\S]*?\{winner\}[\s\S]*?null/i.test(respondBody), 'accepting records an agreed draw in the authoritative game state');
ok(/update public\.ludo_chess_matches[\s\S]*?update public\.rooms[\s\S]*?status = 'completed'[\s\S]*?update public\.match_history[\s\S]*?winner_id = null[\s\S]*?jsonb_build_object\('version', v_new_version, 'state', v_state\)/i.test(respondBody), 'acceptance commits match state and draw history together with no winner');
ok(/p_response = 'accept' then[\s\S]*?end if;[\s\S]*?update public\.ludo_chess_matches[\s\S]*?state = v_state, draw_offer = null/i.test(respondBody) && /Only the player who offered the draw can withdraw it/i.test(respondBody), 'declining or withdrawing clears the offer while leaving the active game state unchanged');
ok(!/currency_ledger|wallets|post_currency_transaction/i.test(drawSql), 'draw offers do not alter currency or wallet behavior');
ok(/if p_expected_version <> v_version then[\s\S]*?raise exception 'Match state is stale/i.test(respondBody), 'stale draw responses are rejected before offer-side effects');
ok(/update public\.match_history[\s\S]*?where room_id = p_room_id and status = 'active'/i.test(respondBody), 'draw acceptance updates the production active-history row');
ok(/coalesce\(\(v_draw_offer->>'position_version'\)::bigint, -1\) <> v_version - 1/i.test(respondBody), 'responses reject offers bound to an obsolete locked match version');
console.log('\nLudo Chess database and integration static tests passed (' + checks + ' checks).');
