'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const migrations = fs.readdirSync(path.join(root, 'supabase/migrations'));
const name = migrations.find(file => /_ludo_chess\.sql$/.test(file));
assert.ok(name, 'Ludo Chess migration exists');
const sql = read('supabase/migrations/' + name);
const repetitionSql = read('supabase/migrations/20261005011600_chess_repetition_en_passant.sql');
const intendedClaimSql = read('supabase/migrations/20261005033000_ludo_chess_intended_draw_claims.sql');
const online = read('www/js/online.js');
const html = read('www/index.html');
let checks = 0;
function ok(value, message) { assert.ok(value, message); checks++; console.log('  ok -', message); }

ok(/create table if not exists public\.ludo_chess_matches/i.test(sql) && /alter table public\.ludo_chess_matches enable row level security/i.test(sql), 'Chess state has a dedicated table with RLS enabled');
ok(/Room members can read Ludo Chess matches[\s\S]*?room_members[\s\S]*?auth\.uid\(\)/i.test(sql), 'only authenticated room participants can read Chess match state');
ok(/revoke all on public\.ludo_chess_matches from anon, authenticated[\s\S]*?grant select on public\.ludo_chess_matches to authenticated/i.test(sql), 'clients have read-only Chess table access');
ok(/alter table public\.rooms[\s\S]*?ludo_chess[\s\S]*?alter table public\.match_history[\s\S]*?ludo_chess/i.test(sql), 'room and match history constraints include the new mode');
ok(/Ludo Chess requires exactly two seats/i.test(sql) && /v_room\.capacity <> 2 or v_count <> 2/i.test(sql), 'room creation and start enforce exactly two players');
ok(/create or replace function public\.start_room/i.test(sql) && /insert into public\.ludo_chess_matches/i.test(sql), 'the existing ready/host flow initializes a separate Chess state row');
for (const fn of ['ludo_chess_move', 'claim_ludo_chess_draw', 'resign_ludo_chess']) {
  ok(new RegExp('create or replace function public\\.' + fn + '\\(', 'i').test(sql), fn + ' is a dedicated RPC');
  ok(new RegExp('grant execute on function public\\.' + fn + '\\(', 'i').test(sql), fn + ' is available to authenticated players');
}
const moveStart = sql.indexOf('create or replace function public.ludo_chess_move(');
const moveEnd = sql.indexOf('$$;', moveStart);
const moveBody = sql.slice(moveStart, moveEnd);
ok(moveBody.indexOf('public.rooms as r') < moveBody.indexOf('public.ludo_chess_matches as m') && moveBody.indexOf('public.ludo_chess_matches as m') < moveBody.indexOf('private.online_match_actions as a'), 'move RPC locks room and state before idempotency lookup');
ok(/auth\.uid\(\)[\s\S]*?You are not a member of this room[\s\S]*?v_state->>'turn'[\s\S]*?v_seat/i.test(moveBody), 'move RPC verifies authentication, room membership, and the assigned turn');
ok(/p_expected_version <> v_version[\s\S]*?private\.ludo_chess_legal/i.test(moveBody), 'move RPC rejects stale versions and independently validates legal moves');
ok(/primary key \(room_id, action_id\)/i.test(read('supabase/migrations/20261004100500_online_authoritative_match.sql')) && /v_existing\.actor_id <> v_user or v_existing\.request <> v_request/i.test(moveBody), 'Chess actions reuse actor- and payload-bound idempotency');
ok(/en.passant/i.test(sql) && /castling/i.test(sql) && /p_promotion/i.test(sql) && /checkmate/i.test(sql) && /stalemate/i.test(sql), 'server rules cover en passant, castling, promotion, checkmate, and stalemate');
ok(/draw_seventy_five_moves/i.test(sql) && /draw_fivefold_repetition/i.test(sql) && /draw_insufficient_material/i.test(sql) && /claimable/i.test(sql), 'server recognizes automatic and claimable standard draw conditions');
const drawClaimableStart = sql.indexOf('create or replace function private.ludo_chess_draw_claimable(');
const drawClaimableEnd = sql.indexOf('$$;', drawClaimableStart);
const drawClaimableBody = sql.slice(drawClaimableStart, drawClaimableEnd);
ok(/p_state->>'phase' <> 'active' then return false/i.test(drawClaimableBody), 'server draw claims cannot override checkmate, stalemate, or automatic terminal draws');
ok(/if not v_has_move then[\s\S]*?checkmate[\s\S]*?stalemate[\s\S]*?else[\s\S]*?v_halfmove >= 150[\s\S]*?v_repetitions >= 5[\s\S]*?ludo_chess_insufficient/i.test(sql), 'server evaluates checkmate or stalemate before automatic 75-move, fivefold, and insufficient-material draws');
ok(/if v_state->>'phase' = 'over' then[\s\S]*?update public\.match_history set status = 'completed',winner_id = v_winner,result = pg_catalog\.jsonb_build_object\('version',v_new_version,'state',v_state\)/i.test(moveBody), 'server persists checkmate, stalemate, and automatic draw state/results in match history');
const currentClaimStart = sql.indexOf('create or replace function public.claim_ludo_chess_draw(');
const currentClaimEnd = sql.indexOf('$$;', currentClaimStart);
const currentClaimBody = sql.slice(currentClaimStart, currentClaimEnd);
ok(/private\.ludo_chess_draw_claimable\(v_state\)[\s\S]*?update public\.ludo_chess_matches[\s\S]*?update public\.rooms[\s\S]*?update public\.match_history[\s\S]*?winner_id=null[\s\S]*?result=pg_catalog\.jsonb_build_object\('version',v_new_version,'state',v_state\)/i.test(currentClaimBody), 'the current-position claim RPC authoritatively completes and records the draw result');
ok(/private\.ludo_chess_legal\(p_state, v_from, v_ep, null\)/i.test(repetitionSql), 'server repetition identity preserves en-passant only when a legal capture is available');
ok(/create or replace function private\.ludo_chess_normalize_position_key/i.test(repetitionSql) && /split_part/i.test(repetitionSql), 'server can normalize legacy repetition-history keys');
ok((repetitionSql.match(/private\.ludo_chess_normalize_position_key\(h\.value\)\s*=\s*v_key/gi) || []).length === 2, 'draw claims and automatic fivefold detection both count normalized history keys');
const intendedClaimStart = intendedClaimSql.indexOf('create or replace function public.claim_ludo_chess_draw_by_move(');
const intendedClaimEnd = intendedClaimSql.indexOf('$$;', intendedClaimStart);
const intendedClaimBody = intendedClaimSql.slice(intendedClaimStart, intendedClaimEnd);
ok(intendedClaimStart >= 0 && /security definer set search_path = ''/i.test(intendedClaimBody), 'intended-move claims use a dedicated fixed-search-path security-definer RPC');
ok(/auth\.uid\(\)[\s\S]*?room_members[\s\S]*?public\.rooms[\s\S]*?public\.ludo_chess_matches[\s\S]*?private\.online_match_actions/i.test(intendedClaimBody), 'intended-move claims authenticate membership and serialize room, state, and idempotency checks');
ok(/p_expected_version <> v_version/i.test(intendedClaimBody) && /v_state->>'turn'\)::integer <> v_seat/i.test(intendedClaimBody), 'intended-move claims reject stale versions and out-of-turn players');
ok(/private\.ludo_chess_apply\(v_state, p_from, p_to, p_promotion\)/i.test(intendedClaimBody) && /private\.ludo_chess_draw_claimable\(v_candidate\)/i.test(intendedClaimBody), 'the server independently validates the legal intended move and resulting claimability');
ok(/draw_fifty_move_claim/i.test(intendedClaimBody) && /draw_threefold_claim/i.test(intendedClaimBody) && /intended_move/i.test(intendedClaimBody), 'the terminal state records the exact claim basis and intended move without applying it');
ok(/update public\.ludo_chess_matches[\s\S]*?update public\.rooms[\s\S]*?update public\.match_history[\s\S]*?status = 'completed'[\s\S]*?result = pg_catalog\.jsonb_build_object\('version', v_new_version, 'state', v_state\)/i.test(intendedClaimBody), 'a successful intended-move claim atomically completes the authoritative state, room, and match-history result');
ok(/revoke all on function public\.claim_ludo_chess_draw_by_move[\s\S]*?from public, anon/i.test(intendedClaimSql) && /grant execute on function public\.claim_ludo_chess_draw_by_move[\s\S]*?to authenticated/i.test(intendedClaimSql), 'only authenticated clients can call the new intended-move claim RPC');
ok(/alter publication supabase_realtime add table public\.ludo_chess_matches/i.test(sql), 'Chess state is added to Realtime publication');
ok(/table: 'ludo_chess_matches'/i.test(online) && /ludo_chess_move/i.test(online) && /claim_ludo_chess_draw_by_move/i.test(online), 'the signed-in client subscribes to Chess state and submits intended claims through the server RPC');
ok(/online-chess-play-claimable-move/i.test(html) && /value="ludo_chess"/i.test(html) && /online-chess-board/i.test(html), 'the Chess UI offers explicit claim-or-play choices for an intended draw move');
ok(!/ludo_chess|LudoChess/.test(read('www/js/logic.js') + read('www/js/save-store.js')), 'Classic Ludo engine and local save format are not changed by Chess');
console.log('\nLudo Chess database and integration static tests passed (' + checks + ' checks).');
