'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const migrationsDir = path.join(root, 'supabase/migrations');
const migrationNames = fs.readdirSync(migrationsDir);
const baseName = migrationNames.find(name => /_online_backend\.sql$/.test(name));
const profilesName = migrationNames.find(name => /_profiles_realtime\.sql$/.test(name));
assert.ok(baseName, 'base backend migration exists');
assert.ok(profilesName, 'profile Realtime migration exists');
const migration = read('supabase/migrations/' + baseName);
const profileMigration = read('supabase/migrations/' + profilesName);
const app = read('www/js/online.js');
const config = read('www/js/supabase-config.js');
const html = read('www/index.html');
const manifest = read('android/app/src/main/AndroidManifest.xml');
const privacy = read('PRIVACY.md');
const setup = read('docs/online-backend-setup.md');
let checks = 0;
function ok(value, message) {
  assert.ok(value, message);
  checks++;
  console.log('  ok -', message);
}

ok(!/pg_catalog\.(?:coalesce|nullif|greatest|least)\s*\(/i.test(migration), 'PostgreSQL special forms are not incorrectly schema-qualified');
const tables = ['profiles', 'wallets', 'currency_ledger', 'rooms', 'room_members', 'room_invites', 'match_history'];
for (const table of tables) {
  ok(new RegExp('create table if not exists public\\.' + table + '\\b', 'i').test(migration), table + ' table is in the migration');
  ok(new RegExp('alter table public\\.' + table + ' enable row level security', 'i').test(migration), table + ' has RLS enabled');
}
ok(/revoke all on public\.profiles,[\s\S]*?from anon, authenticated/i.test(migration), 'client table DML is revoked before narrow grants');
ok(/grant update \(display_name\) on public\.profiles to authenticated/i.test(migration), 'authenticated users can update only their display name');
ok(/create policy "Users can read their own wallet"[\s\S]*?auth\.uid\(\)[\s\S]*?user_id/i.test(migration), 'wallet reads are owner-scoped');
ok(/create or replace function public\.post_currency_transaction[\s\S]*?security definer[\s\S]*?set search_path = ''/i.test(migration), 'currency changes run inside a fixed-search-path security-definer function');
ok(/revoke all on function public\.post_currency_transaction\(uuid, text, bigint, text, text\) from public, anon, authenticated/i.test(migration), 'currency transaction function is unavailable to app clients');
ok(/grant execute on function public\.post_currency_transaction\(uuid, text, bigint, text, text\) to service_role/i.test(migration), 'currency function is service-role-only');
ok(/grant execute on function public\.finalize_match\(uuid, uuid, jsonb\) to service_role/i.test(migration), 'match finalization is server-only');
ok(/unique \(user_id, event_key\)/i.test(migration) && /for update/i.test(migration), 'currency mutations have an idempotency key and wallet row lock');
ok(/status = 'waiting'[\s\S]*?for update[\s\S]*?skip locked/i.test(migration), 'matchmaking claims a waiting room under a row lock');
ok(/create policy "Room members can read their room"[\s\S]*?private\.is_room_member/i.test(migration), 'room reads require room membership');
ok(/alter publication supabase_realtime add table/i.test(migration), 'lobby tables are conditionally added to Realtime publication');
ok(/tablename = 'profiles'[\s\S]*?alter publication supabase_realtime add table public\.profiles/i.test(profileMigration), 'profile Realtime is added idempotently in a separate migration');
ok(!/sb_secret_[A-Za-z0-9_-]{12,}/i.test(config + app) && !/(?:service_role|serviceKey)[_-]?key\s*[:=]\s*['"][^'"]+['"]/i.test(config + app), 'browser files contain no embedded service-role/secret key');
ok(/url:\s*'https:\/\/exggyvbsqhoasrqgzerf\.supabase\.co'/.test(config) && /publishableKey:\s*"sb_publishable_/.test(config), 'frontend points only to the verified project with its public publishable key');
ok(/emailPasswordEnabled:\s*true/.test(config) && !/oauthProviders/.test(config), 'frontend config enables email/password only and has no social-provider flags');
ok(/id="online-email" type="email"/.test(html) && /id="online-password" type="password"/.test(html) && /id="online-auth-form"/.test(html), 'portal has user-entered email/password sign-in fields');
ok(/id="online-signup"/.test(html) && /id="online-reset-request"/.test(html) && /id="online-recovery-form"/.test(html), 'portal exposes signup, reset-request, and recovery-password forms');
ok(!/darkshadowwon@gmail\.com/i.test(html + app + config), 'user email is not hardcoded into web source or configuration');
ok(!/signInWithOAuth|oauthProviders|online-google|online-facebook|providerEnabled/.test(app + html + config), 'portal contains no Google/Facebook OAuth controls or calls');
ok(/signInWithPassword\(/.test(app) && /auth\.signUp\(/.test(app) && /resetPasswordForEmail\(/.test(app) && /auth\.updateUser\(\{ password: password \}\)/.test(app), 'email/password sign-in, signup, reset, and password update use Supabase Auth');
ok(/passwordField\.value = ''/.test(app) && /\$\('online-password'\)/.test(app), 'password inputs are cleared after auth requests');
ok(/emailRedirectTo: authRedirectUrl\(\)/.test(app) && /resetPasswordForEmail\([\s\S]*?redirectTo: authRedirectUrl\(\)/.test(app), 'signup and reset links return through the configured web/mobile redirect');
ok(/event === 'PASSWORD_RECOVERY'/.test(app) && /exchangeCodeForSession/.test(app), 'web and Android email auth callbacks support recovery and confirmation');
ok(!/cdn\.jsdelivr\.net\/npm\/@supabase/.test(html) && /document\.createElement\('script'\)/.test(app), 'Supabase SDK is absent from startup markup and loads lazily');
ok(/table: 'room_members'/.test(app) && /function subscribeProfile/.test(app) && /table: 'profiles'/.test(app), 'lobby roster and visible profiles refresh from Realtime');
ok(/function subscribeHistory/.test(app) && /table: 'match_history'/.test(app), 'participant-visible match history refreshes from Realtime');
ok(/table: 'wallets', filter: 'user_id=eq\.' \+ currentUser\.id/.test(app) && /'wallets'/.test(migration), 'cloud balance updates use an owner-filtered Realtime subscription');
ok(/online-lobby\.browser\.test\.js/.test(read('package.json')), 'browser integration test is discoverable from npm scripts');
ok(/com\.offerpk\.offlineludo/.test(manifest) && /auth-callback/.test(manifest), 'Android retains the email confirmation/reset deep link');
ok(/Shared board state, dice and turn-by-turn gameplay are not enabled/.test(html), 'online UI discloses the current lobby-only gameplay boundary');
ok(/Do not treat local coins and online balances as interchangeable/i.test(privacy) && /does not hardcode the address or save the raw password/i.test(privacy), 'privacy notice separates local balances and passwords from local saves');
ok(/exggyvbsqhoasrqgzerf/.test(setup) && /email\/password provider is enabled/i.test(setup) && /SMTP setup is intentionally deferred/i.test(setup), 'setup guide records the verified email-auth and mail-delivery status');
ok(/project-team addresses/i.test(app) && /only delivers to addresses in the project's team/i.test(setup) && /intentionally deferred/i.test(setup), 'UI and setup guide disclose team-only default email delivery and deferred SMTP');
ok(/existing local game modes and saves retained/i.test(read('README.md')), 'product docs preserve offline play and saves');
ok(/signUp\(|resetPasswordForEmail\(|PASSWORD_RECOVERY/.test(read('test/online-lobby.browser.test.js')), 'browser suite covers signup and email/password recovery paths');
console.log('\nOnline backend static validation passed (' + checks + ' checks).');
