'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const css = read('www/css/style.css'), game = read('www/js/game.js'), tokenSystem = read('www/js/token-system.js');
const html = read('www/index.html'), online = read('www/js/online.js'), saveStore = read('www/js/save-store.js'), pkg = JSON.parse(read('package.json'));
let checks = 0;
function ok(value, message) { assert.ok(value, message); checks++; console.log('  ok - ' + message); }
console.log('tall-pawns.test.js');
ok(pkg.version === '1.7.3', 'feature patch version is aligned');
const pcRule = css.match(/\.pc \{[^}]+\}/);
ok(!!pcRule && /width: calc\(var\(--cell\) \* \.54\)/.test(pcRule[0]) && /height: calc\(var\(--cell\) \* \.88\)/.test(pcRule[0]), 'latest-main token-button hitbox dimensions are unchanged');
ok(/margin: calc\(var\(--cell\) \* -\.70\) 0 0 calc\(var\(--cell\) \* -\.27\)/.test(pcRule[0]), 'token anchor and board-coordinate margins are unchanged');
ok(/function buildPieces\(\)[\s\S]*?TokenSystem\.svgMarkup/.test(game), 'shared Ludo modes use the procedural circular TokenSystem renderer');
ok(/viewBox="0 0 24 24"/.test(tokenSystem) && /<circle class="gem-body"/.test(tokenSystem), 'live token body retains circular geometry');
ok(/gem-rim-outer/.test(tokenSystem) && /gem-body/.test(tokenSystem) && /gem-num-disc/.test(tokenSystem) && /gem-set-mark/.test(tokenSystem), 'rim, crystal, raised number, and set emblem are all retained');
ok(/TOKEN_MATERIAL_ORDER = \[0, 2, 1, 3\]/.test(game) && /id: 'ruby'/.test(game) && /id: 'emerald'/.test(game) && /id: 'gold'/.test(game) && /id: 'sapphire'/.test(game), 'Ruby, Gold, Emerald, and Sapphire metals are distinct');
ok(/TOKEN_CAPTURE_MS = 680/.test(game) && /token-capture-wave/.test(game) && /capture-settle/.test(game), 'impact, shockwave, vanish, and settle remain short and non-blocking');
ok(/function sendToBase[\s\S]*?prefersReducedMotion\(\)/.test(game) && /prefers-reduced-motion: reduce/.test(css), 'capture feedback honors reduced-motion preference');
ok(/token-trail-dot/.test(css) && /function trailColors/.test(tokenSystem), 'skin/set-themed movement trails are short and data-driven');
ok(['mystery', 'lucky', 'quick', 'team', 'arrow', 'friendly'].every(mode => new RegExp('data-mode="' + mode + '"').test(html)), 'all pre-existing shared offline Ludo modes remain available');
ok(/if \(isChess\)[\s\S]*?renderChessBoard[\s\S]*?return;/.test(online) && /presentOnline\(/.test(online), 'Online Classic uses shared identity rendering while Chess retains its separate branch');
ok(/tokenIdentity/.test(game) && /normalizeProgress/.test(game) && /var VERSION = 3/.test(saveStore) && /crossfour\.save\.v' \+ version/.test(saveStore), 'identity and free match progress persist in existing versioned local save');
ok(/Only completed matches advance evolution/.test(game) && !/coins|diamonds|purchase/i.test(game.slice(game.indexOf('function renderTokenShop'), game.indexOf('function renderSkins'))), 'Token 2.0 selection/progression contains no spending path');
ok(/aria-label.*material.*skin\.name.*set\.name.*tier\.name/.test(game), 'screen-reader token label includes material, skin, set, level, position, and move hint');
ok(/js\/token-system\.js\?v=1\.7\.3/.test(html) && /Crossfour v1\.7\.3/.test(html), 'asset cache and release label are aligned');
console.log('\n' + checks + ' Token geometry checks passed.');
